package use_case.frontpage;

import java.util.List;

public class FrontPageResponseModel {
    /**
     * The response model generated by the interactor for front page to
     * be passed to the presenter to update UI by adding or removing
     * prior target users.
     */
    List<String> TargetUsers;

    public FrontPageResponseModel(List<String> targetUsers){
        this.TargetUsers = targetUsers;
    }

    public List<String> getTargetUsers(){
        return TargetUsers;
    }
}
