package use_case_frontpage;

import database.csvManager;
import entity.User;

public class FrontPageRequestModel {
    /**
     * The request model generated by the controller to be passed to the interactor
     * to be processed.
     */
    private final String target;

    public FrontPageRequestModel(String target){
        this.target = target;
    }

    public String getTarget() {
        return target;
    }
}
