package use_case_frontpage;

public class FrontPageRequestModel {
    /**
     * The request model generated by the controller to be passed to the interactor
     * to be processed.
     * Request the presenter to update the chat screen.
     */
    public FrontPageRequestModel(){
    }
}
