package use_case_frontpage;

import java.util.ArrayList;

public class FrontPageResponseModel {
    /**
     * The response model generated by the interactor for front page to
     * be passed to the presenter to update the view by adding or removing
     * prior target users.
     */
    ArrayList<String> TargetUsers;

    public FrontPageResponseModel(ArrayList<String> targetUsers){
        this.TargetUsers = targetUsers;
    }

    public ArrayList<String> getTargetUsers(){
        return TargetUsers;
    }
}
