package use_case_frontpage;

import java.util.ArrayList;

public class FrontPageViewModel {
    /**
     * The view model generated by the presenter to be passed to the view and
     * update the lists of target users that the user will see.
     */
    public ArrayList<String> targetIdList;

    public FrontPageViewModel(ArrayList<String> targetIdList){
        this.targetIdList = targetIdList;
    }

    public ArrayList<String> getMessages() {
        return targetIdList;
    }
}
