package use_case_message;

import java.util.ArrayList;

public class MessageViewModel {
    /**
     * The view model generated by the presenter to be passed to the view and
     * update the chat history of the two users.
     */
    public ArrayList<String> Messages;

    public MessageViewModel(ArrayList<String> messages){
        this.Messages = messages;
    }

    public ArrayList<String> getMessages() {
        return Messages;
    }
}
