package use_case_message;

import entity.ChatHistory;

public class MessageResponseModel {
    /**
     * The response model generated by the interactor for chat page to
     * be passed to the presenter to update the view by adding the new
     * messages sent or loading the chat history.
     */
   ChatHistory chatHistory;

    public MessageResponseModel(ChatHistory chatHistory){
        this.chatHistory = chatHistory;
    }
    public ChatHistory getChatHistory() {
        return chatHistory;
    }
}
